import React from 'react';

const About = () => {
    return (
        <div>
            <h1>About Us</h1>
            <p>Welcome to our website. We are dedicated to providing the best service possible.
            (i) My Hobby
Introduction-Hobby is a fondness for something. It is not a regular work or business. Everyone in this world has one hobby or the other. It is so because a hobby gives us joy and happiness. It is the best use of one's own leisure.
Kinds of Hobbies: Hobbies are of different kinds. Some of them are stamp-collecting, gardening, card-playing, photography, carpentry, painting, riding, singing and knitting. Many more subjects can be added to this list. One is free to choose his own hobby from this long list of hobbies.
My Hobby- My hobby is gardening. There is a small plot in front of my house. I have turned this plot into a garden. This small but beautiful garden is the result of my brother's and my labour. I work in the garden every morning and evening. I dig the land, make beds for flowers and vegetables and plants a good variety of flowers and other kinds of plants. Now, there are rose, lily, marigold and many other flowers in my garden. I have also two trees in my garden. Creepers and plants in my garden are the best in the colony. I grow some pumpkins, brinjals and potatoes in the garden. Thus, my garden gives me flowers and many other things.
My hobby is very useful. It keeps me busy and teaches me the importance of physical labour. I learn things myself by doing them with my hands. It leads me to dignity of labour.
Conclusion: My garden gives us flowers which are used in 'Puja'. I oblige my friends and relatives by giving them vegetables grown in my garden. Sometimes, I take part in flower competitions and win prizes.
Thus, my hobby brings joy and happiness to all. I am proud of my garden and my hobby. It gives me physical exercise and keep me fit all day long. Gardening makes me feel godliness.
(ii) Cinema-its merits and demerits:
The Cinema is an outstanding wonder of this modern age. Apart from the great pleasure it gives us an usual as a means of entertainment it is in many ways an education in itself.
The Cinema is also very valuable asset to educationists in imparting knowledge. the film companies from time to time produce historical pictures and these pictures are of great assistance to the teacher of history. Even some of Shakespeare's great dramas and comedies have been filmed. We thereby gain a much better idea of the play than would be possible from a causal reading of it.
The great importance of cinema is in the use of the film in the teaching of science and industry. There are educational film companies which devote their time to the filming of the lives and habits of animals, insects, fishes, germs and numerous other forms of life. We can see the hatching of eggs of fish and their development into large fishes. We can watch the unpleasing activity of many kind of germs and their effect on water, milk or blood. We can watch the opening and closing of flowers and leaves and growth of grass and weeds. All these actions and movements and greatly magnified on the screen. Such pictures are intensely interesting and are a great help in the cause of education.
In India we have a number of film companies producing very interesting films in Indian languages. Epic stories, historical plays and social dramas are successfully dealt with by our film producers.
The cinema is a cheap and fine source of amusement. Our life is busy. We want some relief from dull and routine work. The cinema is the most popular means of entertainment. Beautiful scenes, sweet songs and thrilling dances make us happy and forget the real world for some time and we are lost in the world of beauty and joy.
The cinema has its educative value too. A good film teaches us lots of lessons. It may tell us sometimes about history, geography, biology, hygiene and other things. We see the new countries, rivers, mountains etc., in a film. We see the dresses, customs, festivals etc., of people in different regions or countries. A film can teach us something of literature, philosophy and economics. Moreover, teaching through pictures is more lasting in the memory than teaching through books.
The cinema has an adverse effect on public morals. The lure of the cinema is so great that boys often steal to purchase the ticket and often tell a lie to their parents. Students may often be seen leaving their in order to enjoy a matinee the dirty songs, dances and love scenes so common in India films, corrupt the public morals and have an exciting on the young. They become sex conscious at an early age.
The cinema creates dissatisfaction with ones parents potion and status in life. In the pictures, the hero and the heroine are often shown rolling in wealth. They live in big and well furnished house, ride in cars, and have the most fashion clothes to wear. They seem to have nothing to do except make love and enjoy. All the show of wealth and comfort, naturally makes those persons dissatisfied who are not so favourably placed. They also want to enjoy like the characters of the film; and hence lose all happiness in their present life. This evil effect of the cinema is clearly seen in the behaviour of a large number of boys and girls who run away from their homes to become heroes and heroines.
The cinema also increases crime. People learn from it new methods of community crime. Many film glorify the career of criminal. He is often represented as a great hero who does brave deeds. This obviously has an adverse effects specially on those whose minds are immature and who can not think of themselves.
But the evil effect should not make us forget its many advantages. It is well known that it is important means of reaction. We can even say that for the poor masses of India. It is the only means of amusement. It is cheap and so within the reach of everyone. Besides the film provides entertainment for persons of all tastes. Musics, dance and dialogue and story are all combined in one, so that everyone can find something to amuse him in cinema film.
(iii) An interesting Match I witnessed:
Introduction: Every boy likes to see matches. I am very fond to seeing cricket matches. I saw the One day cricket match between West Indies and India, played in Nehru Stadium, Indore. Some of my friends and I went to see the match. There was a huge crowd. India was the winner team in a Prudential world cup tournament in England and West Indies was the runner up. So it was the match of prestige.
At the stadium: The crowd was uncontrollable and it seemed impossible to get the tickets. After a heavy trouble, we got tickets and entered the stadium. At 1010 a.m. the match started. Indian Captain Kapildev won the toss and chose batting.
Indian batting: The opening batsmen Sunil Gavaskar and Shrikant started batting. But after making a few runs both were out one by one. Shrikant made two fours and was L.B.W. out. Gavaskar was also out after making 1515 runs with three fours.
When Shrikant was out Mr. Vengsarkar came for batting and after Gavaskar, Sandeep Patil and Vengsarkar played some fine strokes and made good runs for the team. They brought the score upto 110110. Patil was out by Marshal. In place of Patil, Captain Kapildev came.
Kapildev and Madanlal brought the score upto 200200 runs. After his pair the rest of the players Yashpal, Kirmani, Sandhu and Binny were out adding only 4040 runs and the Indian team was all out an 240240 runs.
West Indies batting-Now West Indies team came to bat. Gorden Grainage and Desmond Hans came to play. They needed only 241241 runs to win the match. The opening pair played well. They made 126126 runs. But Kapildev took the wicket of Hans. Richards came and this pair could not be removed by the Indian bowlers. They played beautiful strokes and made 241 241 losing only one wicket of Hans. West Indies won the match.
(iv) Value of travelling:
Travelling means going from place to place for one or another purpose. Some people travel for pleasure, some for business, while there are many others who travel to earn their living.
Traveling is rather a tedious and troublesome job for people of small means. Because, they cannot afford to pay for comfortable conveyance and therefore are huddled in trains and buses and one is put to a thousand inconveniences. Rich people, on the other hand find travelling very enjoyable. They can bear the high cost of travelling and enjoy all the amenities on the way. They can feast their eyes with the beauties of nature. When they go to a particular place they ordinarily put up at the costliest place and come into contact with people of high status.
Travelling is instructive to one and all. When we travel from one place to another we meet will people of various places with various habits, manners and customs. We carry our own culture to them and in return, come back with their culture. Thus a link is established between two places and grows better understanding and close relations among different groups of people.
In countries of Europe and America, travelling is regarded as a point of education for the young people. They think that education is incomplete till a young man goes aboard and comes into direct contact with the people of various countries. No guardians would afford the expenses of such a travel. But the poor Indians cannot even think of such a luxury. We are so poor that our parents cannot carry us through to the competition of education. We therefore, have to remain satisfied with the study of books on the subject.
            </p>
        </div>
    );
};

export default About;